### ISSUE TITLE
Update body of PhD Projects

### ISSUE THREAD

**Issue by cartoonist** [ALPACA-ITN/alpaca-itn.eu#11]

**Comment by cartoonist** [comment]
- [x] Remove "Application deadline" and "Link for application" lines

**Comment by Harsha-madyastha** [comment]
Removed the parts

**Comment by cartoonist** [comment]
For me they are still visible. For example in [here](https://alpaca-itn.eu/job-offer-cnrs):
![Image](https://user-images.githubusercontent.com/1281559/177515961-75d511de-b20c-465c-8490-9bffb6f48ec2.png)

**Comment by Harsha-madyastha** [comment]
Sorry, I misunderstood with another form. Now the above parts are removed.

**Comment by cartoonist** [comment]
No problem. Thanks!

**Comment by cartoonist** [comment]
I also added the ESR working on each project.
