### ISSUE TITLE
Add the profile for the new affiliated member

### ISSUE THREAD

**Issue by cartoonist** [ALPACA-ITN/alpaca-itn.eu#27]
Fawaz Dabbaghie has joined the project as an affiliated member. I have asked his info and photo and I will add to the https://github.com/ALPACA-ITN/profiles. We need to add his profile as soon as we receive the info from him.

**Comment by cartoonist** [comment]
I've just added his profile information.

**Comment by Harsha-madyastha** [comment]
Added
