### ISSUE TITLE
Add list of PIs

### ISSUE THREAD

**Issue by cartoonist** [ALPACA-ITN/alpaca-itn.eu#4]

**Comment by cartoonist** [comment]
Here is the list of ALPACA members grouped by their roles: [alpaca-team.ods](https://github.com/ALPACA-ITN/alpaca-itn.eu/files/8819339/alpaca-team.ods)

**Comment by cartoonist** [comment]
- [ ] Add links to PI's websites.

**Comment by Harsha-madyastha** [comment]
All the PI's have been added
